package by.htp.googletest;

import java.util.concurrent.TimeUnit;

import org.openqa.selenium.By;
import org.openqa.selenium.Keys;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.support.ui.ExpectedCondition;
import org.openqa.selenium.support.ui.WebDriverWait;

public class Selenium2Example {
	public static void main(String[] args) {

		System.setProperty("webdriver.chrome.driver", "C:/Chromedriver.exe");
		WebDriver driver = new ChromeDriver();

		driver.get("http://www.mail.ru");

		WebElement login = driver.findElement(By.id("mailbox__login"));
		login.click();
		login.sendKeys("tathtp");

		WebElement psswd = driver.findElement(By.id("mailbox__password"));
		psswd.click();
		psswd.sendKeys("Klopik123");

		WebElement submit = driver.findElement(By.id("mailbox__auth__button"));
		submit.click();

		try {
			Thread.sleep(10000);
		} catch (InterruptedException e) {
			e.printStackTrace();
		}

		WebElement write = driver.findElement(By.xpath("//*/div/div/div[2]/div/a/span"));
		write.click();

		WebElement to = driver.findElement(By.xpath("//*/div[1]/div/div[3]/div[1]/div/div/div[2]/div/div/div"));
		to.click();
		to.sendKeys(" sviatlana.zakharenka@gmail.com");

		WebElement popup = driver.findElement(By.xpath("//*/div[11]/div/div"));
		popup.click();

		WebElement topic = driver.findElement(By.xpath("//*/div[1]/div/div[3]/div[4]/div/div/div[2]/div/input"));
		topic.click();
		topic.sendKeys("Selenium Web Driver Test Message");

		WebElement frame = driver.findElement(By.xpath("//iframe[contains(@id,'composeEditor_ifr')]"));
		driver.switchTo().frame(frame);

		WebElement element = driver.findElement(By.id("tinymce"));
		element.sendKeys("Hi Svetlana.");
		element.sendKeys(" This letter is automatically generated by my selenium test.");
		element.sendKeys(" Please find my homework here https://github.com/igorkan45/Selenium2");
		element.sendKeys(" Have a nice day. Igor Kanunnikov");
		driver.switchTo().defaultContent();

		WebElement button = driver.findElement(By.xpath("//*/div[3]/div/div[2]/div[1]/div"));
		button.click();

	}
}